apiVersion: v1
kind: Template
metadata: {}
parameters:
  - name: NAME_SUFFIX
    required: true
  - name: NAMESPACE
    required: true
  - name: S3_SERVICE
    displayName: the name of the OpenShift service in front of the s3/minio storage provider
    required: true
  - name: PVC_SIZE
    value: "15Gi"
  - name: DEST_PVC
    required: true
  - name: SECRETS
    displayName: "Secret object to reference"
    value: "gwells-minio-secrets"
  - name: VERSION
    value: v1.0.0
  - name: SCHEDULE
    value: "15 3 * * *"
    required: false
  - name: BUCKETS
    value: ""
    displayName: a space separated list of buckets to backup from the remote s3 service
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      finalizers:
      - kubernetes.io/pvc-protection
      name: "gwells-documents-${NAME_SUFFIX}-backup-vol"
      labels:
        app: "gwells-${NAME_SUFFIX}"
        name: "gwells-${NAME_SUFFIX}-documents-backup"
        component: backups
        part-of: gwells
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: ${PVC_SIZE}
      storageClassName: gluster-file
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: gwells-documents-${NAME_SUFFIX}-backup
      namespace: "${NAMESPACE}"
    spec:
      concurrencyPolicy: Forbid
      failedJobsHistoryLimit: 3
      jobTemplate:
        metadata:
          labels:
            app: "gwells-${NAME_SUFFIX}"
            name: "gwells-${NAME_SUFFIX}-documents-backup"
            component: backups
            part-of: gwells
        spec:
          backoffLimit: 10
          template:
            spec:
              activeDeadlineSeconds: 3600
              containers:
              - image: docker-registry.default.svc:5000/${NAMESPACE}/gwells-documents-backup:${VERSION}
                args: "${BUCKETS}"
                imagePullPolicy: Always
                name: minio-backup
                env:
                - name: RCLONE_CONFIG_MINIO_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: ${SECRETS}
                      key: MINIO_ACCESS_KEY
                - name: RCLONE_CONFIG_MINIO_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${SECRETS}
                      key: MINIO_SECRET_KEY
                - name: RCLONE_CONFIG_MINIO_ENDPOINT
                  value: "${S3_SERVICE}"
                volumeMounts:
                - mountPath: /mnt/dest/
                  name: dest
                - mountPath: /backup
                  name: source
                  readOnly: true
              restartPolicy: OnFailure
              terminationGracePeriodSeconds: 30
              volumes:
              - name: dest
                persistentVolumeClaim:
                  claimName: "${DEST_PVC}"
              - name: source
                persistentVolumeClaim:
                  claimName: "gwells-documents-${NAME_SUFFIX}-backup-vol"
      schedule: ${SCHEDULE}
      successfulJobsHistoryLimit: 3
